### ISSUE TITLE
Cubemap bake error causing scenes not to save in editor

### ISSUE THREAD

**Issue by Griffisaurus** [XRFoundation/XREngine#5999]
Saving sometimes hangs up.  Looks like it’s during the preview cubemap generation.  Seems to happen when making a scene in a project created within the editor.  Have not had the same problem when saving within the default project.

![image](https://user-images.githubusercontent.com/92340542/167469410-6bb7a552-5162-4e68-84c2-6d265e7aee32.png)

**Comment by HexaField** [comment]
This will likely be solved by Kyle's work in making scenes & projects rely on storage provider instead of file system

**Comment by NPatel10** [comment]
@Griffisaurus, Some changes have been merged related to Saving in recent merge. Can you try to recreate this issue at your end? I am not able to do so. If you can recreate please provide me some more steps to work on.

**Comment by Griffisaurus** [comment]
I am still getting it.  
Steps:
open editor
create new project
create new scene
rename scene
load globe theater and globe theatre collission assets
load globe theater cubemap into skybox
save
